# Generated by Django 5.0.7 on 2024-07-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=199, max_digits=9999999.0
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=199, max_digits=9999999.0
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(
                decimal_places=4, default=199, max_digits=9999999.0
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=4, default=299, max_digits=9999999.0
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=199, max_digits=9999999.0
            ),
        ),
    ]
