# Generated by Django 5.0.7 on 2024-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_cartorder_price_alter_cartorderitems_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2, default=299.0, max_digits=999999.0
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=199.0, max_digits=999999.0
            ),
        ),
    ]
