# Generated by Django 5.0.7 on 2024-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_product_old_price_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.IntegerField(default=199, max_length=99999),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.IntegerField(default=199, max_length=99999),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.IntegerField(default=199, max_length=99999),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.IntegerField(default=299, max_length=99999),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=199, max_length=99999),
        ),
    ]
