# Generated by Django 5.0.7 on 2024-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Didsabled"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
