# Generated by Django 5.0.7 on 2024-07-26 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_vendor_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="image",
            new_name="cover_image",
        ),
    ]
