# Generated by Django 5.0.7 on 2024-07-26 11:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_image_vendor_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="image",
            field=models.ImageField(
                default="vendor/default.png", upload_to=core.models.user_directory_path
            ),
        ),
    ]
