# Generated by Django 5.0.7 on 2024-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_productimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="life",
            field=models.IntegerField(blank=True, default=70, max_length=800),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.IntegerField(blank=True, default=100, max_length=100000),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Organic", max_length=100),
        ),
    ]
