# Generated by Django 5.0.7 on 2024-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_product_life_product_stock_count_alter_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type_of_food",
            field=models.CharField(default="Organic", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Frsh Pear", max_length=100),
        ),
    ]
