# Generated by Django 5.0.7 on 2024-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_productreview_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="This is a default description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifiction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="review",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(default="123 Main Street", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=models.TextField(
                blank=True, default="This is a default description", null=True
            ),
        ),
    ]
